runmode: debug
port: :8080
name: goserver
url: http://127.0.0.1:8080
max_ping_count: 10
gormlog: true
jwt_secret: Rtg8BPKNEf2mB4mgvKONGPZZQSaJWNLijxR42qRgq0iBb5
log:
  writers: file,stdout
  logger_level: DEBUG
  logger_file: log/goserver.log
  log_format_text: false
  rollingPolicy: size
  log_rotate_date: 1
  log_rotate_size: 1
  log_backup_count: 7
db:
  name: goserver
  addr: 127.0.0.1:3306
  username: root
  password: root
docker_db:
  name: goserver
  addr: 127.0.0.1:3306
  username: root
  password: root

